exports.START = 'niketa.start'
exports.REQUEST_CANCELATION = 'niketa.request.cancelation'
exports.REQUEST_TEST_RUN = 'niketa.request.test.run'
exports.REQUEST_LINT_FILE = 'niketa.lint.file'
exports.TOGGLE_FORCE_LINT_MODE = 'niketa.toggle.force.lint'
