exports.START = 'niketa.start'
exports.START_AUTO_MODE = 'niketa.start.auto.mode'
exports.REQUEST_CANCELATION = 'niketa.request.cancelation'
exports.REQUEST_TEST_RUN = 'niketa.request.test.run'
exports.REQUEST_LINT_FILE = 'niketa.lint.file'
